/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIdIndexRouteImport } from './routes/$trackId.index'
import { Route as TrackIdVocabRouteImport } from './routes/$trackId.vocab'
import { Route as TrackIdStatsRouteImport } from './routes/$trackId.stats'
import { Route as TrackIdDictionaryRouteImport } from './routes/$trackId.dictionary'
import { Route as TrackIdWeekWeekIdRouteImport } from './routes/$trackId.week.$weekId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdIndexRoute = TrackIdIndexRouteImport.update({
  id: '/$trackId/',
  path: '/$trackId/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdVocabRoute = TrackIdVocabRouteImport.update({
  id: '/$trackId/vocab',
  path: '/$trackId/vocab',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdStatsRoute = TrackIdStatsRouteImport.update({
  id: '/$trackId/stats',
  path: '/$trackId/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdDictionaryRoute = TrackIdDictionaryRouteImport.update({
  id: '/$trackId/dictionary',
  path: '/$trackId/dictionary',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdWeekWeekIdRoute = TrackIdWeekWeekIdRouteImport.update({
  id: '/$trackId/week/$weekId',
  path: '/$trackId/week/$weekId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$trackId/dictionary': typeof TrackIdDictionaryRoute
  '/$trackId/stats': typeof TrackIdStatsRoute
  '/$trackId/vocab': typeof TrackIdVocabRoute
  '/$trackId/': typeof TrackIdIndexRoute
  '/$trackId/week/$weekId': typeof TrackIdWeekWeekIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$trackId/dictionary': typeof TrackIdDictionaryRoute
  '/$trackId/stats': typeof TrackIdStatsRoute
  '/$trackId/vocab': typeof TrackIdVocabRoute
  '/$trackId': typeof TrackIdIndexRoute
  '/$trackId/week/$weekId': typeof TrackIdWeekWeekIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$trackId/dictionary': typeof TrackIdDictionaryRoute
  '/$trackId/stats': typeof TrackIdStatsRoute
  '/$trackId/vocab': typeof TrackIdVocabRoute
  '/$trackId/': typeof TrackIdIndexRoute
  '/$trackId/week/$weekId': typeof TrackIdWeekWeekIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$trackId/dictionary'
    | '/$trackId/stats'
    | '/$trackId/vocab'
    | '/$trackId/'
    | '/$trackId/week/$weekId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$trackId/dictionary'
    | '/$trackId/stats'
    | '/$trackId/vocab'
    | '/$trackId'
    | '/$trackId/week/$weekId'
  id:
    | '__root__'
    | '/'
    | '/$trackId/dictionary'
    | '/$trackId/stats'
    | '/$trackId/vocab'
    | '/$trackId/'
    | '/$trackId/week/$weekId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TrackIdDictionaryRoute: typeof TrackIdDictionaryRoute
  TrackIdStatsRoute: typeof TrackIdStatsRoute
  TrackIdVocabRoute: typeof TrackIdVocabRoute
  TrackIdIndexRoute: typeof TrackIdIndexRoute
  TrackIdWeekWeekIdRoute: typeof TrackIdWeekWeekIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$trackId/': {
      id: '/$trackId/'
      path: '/$trackId'
      fullPath: '/$trackId/'
      preLoaderRoute: typeof TrackIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$trackId/vocab': {
      id: '/$trackId/vocab'
      path: '/$trackId/vocab'
      fullPath: '/$trackId/vocab'
      preLoaderRoute: typeof TrackIdVocabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$trackId/stats': {
      id: '/$trackId/stats'
      path: '/$trackId/stats'
      fullPath: '/$trackId/stats'
      preLoaderRoute: typeof TrackIdStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$trackId/dictionary': {
      id: '/$trackId/dictionary'
      path: '/$trackId/dictionary'
      fullPath: '/$trackId/dictionary'
      preLoaderRoute: typeof TrackIdDictionaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$trackId/week/$weekId': {
      id: '/$trackId/week/$weekId'
      path: '/$trackId/week/$weekId'
      fullPath: '/$trackId/week/$weekId'
      preLoaderRoute: typeof TrackIdWeekWeekIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TrackIdDictionaryRoute: TrackIdDictionaryRoute,
  TrackIdStatsRoute: TrackIdStatsRoute,
  TrackIdVocabRoute: TrackIdVocabRoute,
  TrackIdIndexRoute: TrackIdIndexRoute,
  TrackIdWeekWeekIdRoute: TrackIdWeekWeekIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
